# Generated by Django 3.2.9 on 2022-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('CNIC', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='National ID Card Number')),
                ('full_Name', models.CharField(max_length=50, verbose_name='Full Name of the Owner')),
                ('phone_numer', models.CharField(max_length=11)),
                ('citizen_of', models.CharField(max_length=5, verbose_name='Select the Country')),
                ('address_of_owner', models.CharField(max_length=100)),
            ],
        ),
    ]
