# Generated by Django 3.2 on 2022-03-07 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('Vehicle_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Vehicle_name', models.CharField(max_length=128)),
                ('Model_number', models.CharField(max_length=30)),
                ('Chasis_number', models.CharField(max_length=30)),
                ('Engine_number', models.CharField(max_length=30)),
                ('Vehicle_type', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.owner')),
            ],
        ),
    ]
