# Generated by Django 3.2.9 on 2022-03-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vehicledetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetail',
            name='Vehicle_name',
        ),
        migrations.AlterField(
            model_name='owner',
            name='citizen_of',
            field=models.CharField(max_length=10, verbose_name='Select the Country'),
        ),
    ]
